package org.example;

public enum AttackResult {
    HAS_NO_WEAPON, WEAPON_WITHOUT_BULLET, ROOM_WITHOUT_ENEMY, CANT_FOUND_ENEMY_WITH_NAME,
    ATTACK_AND_ENEMY_DIED, ATTACK_AND_ENEMY_ALIVE_COUNTER_ATTACK,
    ENEMY_COUNTER_ATTACK_AND_PLAYER_DIED;
}